### ISSUE TITLE
The metrics of depth estimation

### ISSUE THREAD

**Issue by jytime** [weixk2015/DeepSFM#4]
Hi Xingkui,

Thanks for your great work first.

I am curious about the abs_rel and l1_rel used in these SFM papers. If I understand it correctly, l1_rel seems to be just abs_rel (according to DEMON, equation 9). However, regarding abs_rel, I noticed that DeepSFM largely outperforms DPSNet in Sun3D (0.072 vs 0.1470) and RGBD (0.126 vs 0.1470) datasets. In my humble opinion, DPSNet with gt poses should be the upper bound of DeepSFM. I guess DeepSFM's better result is because the iterative refinement, is it right?

Besides, I am trying to report the metrics mentioned below in my work. After getting pose_init from DEMON, my reproduced DeepSFM results are not that good. It would be appreciated if you can provide the results for the datasets in Table 1.

https://github.com/weixk2015/DeepSFM/blob/d972049c9ec6c68d3b13550d79b90b28ed720cf7/test.py#L140

**Comment by weixk2015** [comment]
That's right, with gt poses, DeepSFM is better than DPSNet because the geometry consistency among views via iterative refinement.
Here is the results I just got. it is slightly different from the paper results due to the retrained checkpoints, 
hyper-parameters setting and slightly uncertainty of DeMoN results. Note that DeMoN pose and depth is scaled by Norm(GT translation)/Norm(DeMoN translation) before being taken as initialization.
Sun3D
   abs_rel,   abs_diff,     sq_rel,        rms,    log_rms,         a1,         a2,         a3,     L1-inv,     sc-inv,   rot, trans
    0.0700,     0.9263,     0.2354,     1.4032,     0.1034,     0.8514,     0.9382,     0.9742,     0.0106,     0.1030, 1.2355,    11.1698
MVS
abs_rel,   abs_diff,     sq_rel,        rms,    log_rms,         a1,         a2,         a3,     L1-inv,   sc-inv,   rot, trans
0.0932,     1.0783,     0.3507,     1.6486,     0.1758,     0.8274,     0.9659,     0.9788,     0.0318,     0.1369,  3.8217, 11.1635
Scenes11
 abs_rel,   abs_diff,     sq_rel,        rms,    log_rms,         a1,         a2,         a3,     L1-inv,   sc-inv,   rot, trans
    0.1046,     2.0572,     1.4157,    1.5351,     0.2293,     0.8084,     0.9587,     0.9829,     0.0086, 0.1180,   0.5706, 3.5291
RGBD
abs_rel,   abs_diff,     sq_rel,        rms,    log_rms,         a1,         a2,         a3,     L1-inv,   sc-inv,   rot, trans
 0.0972,     1.2471,     0.3260,     2.0297,     0.1617,     0.8852,     0.9673,     0.9850,     0.0129,     0.1198,  1.9277, 15.6433

**Comment by jytime** [comment]
Thanks for your quick reply. According to your provided results, DeepSFM is better than DPSNet regarding abs_rel. In the contrast, DPSNet is quite good on the metrics like abs_diff or sq_rel. It is a bit weird. Is there any idea of this observation?

**Comment by weixk2015** [comment]
> Thanks for your quick reply. According to your provided results, DeepSFM is better than DPSNet regarding abs_rel. In the contrast, DPSNet is quite good on the metrics like abs_diff or sq_rel. It is a bit weird. Is there any idea of this observation?

Yes, I noticed that. One possible explanation is that the network is initialized by DeMoN outputs, and because the warping and matching of initialization depths in depth cost volume, the distribution of the output depths of deepSFM is highly related to the distribution of DeMoN results, which tends to perform worse on Abs diff Sq Rel RMSE metrics.

**Comment by jytime** [comment]
Thanks a lot
